### ISSUE TITLE
configuration failure

### ISSUE THREAD

**Issue by marcomaggi** [frejanordsiek/unit-test-tap#1]
On a x86_64-slackware-linux-gnu, after successfully running `autogen.sh`, I get the following error when running `configure`:

```
$./configure --with-vicare=yes
checking for a BSD-compatible install... /usr/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for wheter to target Guile (--with-guile)... no
checking for target Guile effective version (--with-guile-version)... 2.2
checking for whether to target Chicken (--with-chicken)... no
checking for whether to target Vicare (--with-vicare)... yes
checking for gawk... (cached) gawk
checking for a sed that does not truncate output... /usr/bin/sed
./configure: line 2978: syntax error near unexpected token `guile-$v,'
./configure: line 2978: `      PKG_CHECK_EXISTS(guile-$v, GUILE_EFFECTIVE_VERSION=$v, )'
```

According to `git log` I am using commit `c31458969f22b848e9974500973a9380159eacc3`.

**Comment by frejanordsiek** [comment]
What shell are you using? My first guess is that I was writing valid Bash but not valid other-shells code.

**Comment by marcomaggi** [comment]
I am using Bash.  Your package requires a version of `pkg-config` that provides the Autoconf macros; my old version did not.  I have upgraded it.

You should use a file `acinclude.m4` to properly include macro files.  For your package it should look like:
```
### custom macros
m4_include([m4/guile.m4])
m4_include([m4/guile_additional.m4])
m4_include([m4/chicken.m4])
m4_include([m4/vicare.m4])
### end of file
```
After these changes I can get the package to configure successfully.

**Comment by frejanordsiek** [comment]
Ah, pkg-config. Hmm, I do wonder if including the m4 file from it explicitly would save some problems or perhaps including the aclocal.m4 that gets generated.

I was under the impression that starting on line 27 of configure.ac handled that, which is reproduced below. I will look into it. More things in autotools to learn.

```
AC_CONFIG_MACRO_DIR([m4])
m4_include([m4/guile.m4])
m4_include([m4/guile_additional.m4])
m4_include([m4/chicken.m4])
m4_include([m4/vicare.m4])
```

**Comment by marcomaggi** [comment]
In my experience using `acinclude.m4` is not only a matter of style; in the past I found cases in which  macros were not evaluated correctly when defined in an include file loaded by `configure.ac`.  `aclocal.m4` is then processed automatically.
